### ISSUE TITLE
MANLO Rewrite

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_General#1]
Currently the MANLO is way out of date, it still has Griffiths as CoS, I think it might be time for a rewrite

I have a rough draft I am working on because I don't know if we have access to the old one at this point

**Comment by ardenmarshall** [comment]
I wrote this manual when I was DCoS so I have the original word document somewhere. I'd recommend starting one Google doc per manual and starting a discussion on the changes.

This is a good opportunity to completely rethink the way we conduct land operations too

**Comment by assaultboy** [comment]
I think we should consolidate to one document, considering the fact that 411 and 501 are merging ing into 501.

I start sharing the Google doc if people send me their email.

**Comment by ardenmarshall** [comment]
Mine is arden305@gmail.com.

I propose in that case that we just call it the MOPS - Manual of
Operations, and as you say consolidate everything into one document.

**Comment by ardenmarshall** [comment]
I've just found the folder on Google Drive where we write all the new doctrine. We wrote it in google docs before transferring it to work for formatting (I'm anal about that stuff haha).

**Comment by assaultboy** [comment]
Alright I shared my folder with you, feel free to edit whatever, Most of it is just a rough draft

**Comment by ardenmarshall** [comment]
Brilliant, thanks for that.

Just a hint, after sitting down to write the 8 or so manuals that we did,
we found that it's a lot easier to start with a list of contents before
adding paragraphs. That way you don't repeat yourself later :)

So if we lost the chapters we want first, then the sections within each,
then we can write the paragraphs to fill them.
