### ISSUE TITLE
TFAR userconfig file radio_settings.hpp not found

### ISSUE THREAD

**Issue by Dmanwaring** [usecforce/USEC_General#3]
After following the instructions on installing the mods and synchronising the repository, I am unable to proceed on the TFAR installer. Putting in the file path for the userconfig (since the others were already in for me), which on the forum post is stated as "<Arma directory>\USEC\@task_force_radio\userconfig" resulted in the error upon proceeding: "TFAR userconfig file radio_settings.hpp not found".

I looked in an it appears there is no userconfig folder in @task_force_radio, so I instead found it under userconfig\task_force_radio where the radio_settings file was. The same error occurred. I then tried moving the userconfig folder into the @task_force_radio folder, still the same error.

Any changes I tried to make were picked up by the Repository, and after synching it again the problem is not fixed.

**Comment by codethirteen** [comment]
Hop on teamspeak. One of the team will be able to help you configure it. Basically, we used to have userconfig in the repo which is how the docs still read. But what happened is anytime someone made a custom config it was wiped when they updated their modpack. So userconfig now lives outside the repo and is self-configurable. So the repo will give that error, but you should be able to join. If you can get online a bit early you can try connecting to the server and seeing if it lets you. I'll be online soon.

**Comment by Dmanwaring** [comment]
After looking into it more I managed to work out what the installer does, and do it myself by copying configs where they need to be. I tested joining the server and it worked. Thanks for the help!
